//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS_LegalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseParty
    {
        public int CasePartyId { get; set; }
        public int CaseId { get; set; }
        public string PartyType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OrganizationName { get; set; }
        public string Gender { get; set; }
        public string AcademicStatus { get; set; }
        public string SocialStatus { get; set; }
        public string CitizenshipStatus { get; set; }
        public string IUStudentId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> EmailId { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Address Address { get; set; }
        public virtual Email Email { get; set; }
    }
}
