//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS_LegalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intern_Attorney
    {
        public int AttorneyId { get; set; }
        public int InternId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Attorney Attorney { get; set; }
        public virtual Intern Intern { get; set; }
    }
}
