//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLS_LegalServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid US_Id { get; set; }
        public string US_FirstName { get; set; }
        public string US_MiddleName { get; set; }
        public string US_LastName { get; set; }
        public string US_Email { get; set; }
        public string US_Username { get; set; }
        public Nullable<bool> US_IsSuperAdmin { get; set; }
    }
}
